version: '2'
services:
  web:
    build:
      context: .
      dockerfile: webapp.dockerfile
    command: python /webapp/simple_tasklist.py
    volumes:
      - ./webapp:/webapp
    links:
      - db
    extra_hosts:
      - "debug_host:${DOCKER0_IP}" # This is for debugger
  db:
    image: mongo:3.2.9
  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    volumes:
     - ./nginx/nginx.conf:/etc/nginx/conf.d/mysite.template
    ports:
     - "8080:80"
     - "8443:443"
    links:
      - web
    environment:
     - FLASK_PORT=5000
     - SERVER_NAME=0.0.0.0
    command: /bin/bash -c "envsubst '$$SERVER_NAME$$FLASK_PORT' < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"